services:
  app:
    build:
      context: .
      target: build
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    command: npm run dev

  production:
    build:
      context: .
      target: production
    command: npm run start
